name: Static Site

on:
# Test ci --- See https://github.com/Avin15/cs1660-website for grading
  #push:
  #  branches: [ "main" ]
  #pull_request:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - id: 'checkout'
        uses: 'actions/checkout@v4'
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          sparse-checkout: 'website'
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify
      
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/213933799278/locations/global/workloadIdentityPools/id-pool/providers/github'
          service_account: 'github-actions@proud-matter-404620.iam.gserviceaccount.com'

      # upload files to GCS
      - id: 'upload-static-files'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: 'public'
          destination: 'cs1660-final-proj-bucket'
          parent: false
